server:
  port: 8081

owm:
  api:
    key: ${OWM_API_KEY:}

spring:
  datasource:
    url: jdbc:sqlite:/data/weather.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.community.dialect.SQLiteDialect
      hibernate.limit.fetch.first: false